In [6]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv('Admission_Predict_Ver1.1.csv')

In [13]:
df.head(1)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92

In [14]:
df.shape

(500, 9)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         500 non-null    int64
 1   GRE Score          500 non-null    int64
 2   TOEFL Score        500 non-null    int64
 3   University Rating  500 non-null    int64
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.drop(columns=['Serial No.'],inplace=True)

In [20]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [21]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [22]:
X

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [23]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ...
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit , Length: 500, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [25]:
X_train

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
238        310          104                  3  2.0   3.5  8.37         0
438        318          110                  1  2.5   3.5  8.54         1
475        300          101                  3  3.5   2.5  7.88         0
58         300           99                  1  3.0   2.0  6.80         1
380        322          104                  3  3.5   4.0  8.84         1
..         ...          ...                ...  ...   ...   ...       ...
255        307          110                  4  4.0   4.5  8.37         0
72         321          111                  5  5.0   5.0  9.45         1
396        325          107                  3  3.0   3.5  9.11         1
235        326          111                  5  4.5   4.0  9.23         1
37         300          105                  1  1.0   2.0  7.80         0

[400 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X